Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -115,6 +115,15 @@ steps:
               }
           fi
 
+          if [[ "$current_dir" == "security" ]]; then
+              terraform plan -var 'project_id=cloud-build-github-trigger' -var 'governance_project_id=cloud-build-github-trigger' || { 
+                apk add curl
+                echo "{\"body\": \"An error was detected executing \`terraform plan\` against the **/terraform/${env}** directory. Please run \`terraform plan\` locally against that directory to resolve any errors and then resubmit the Pull Request.\"}" > /workspace/api_payload.txt && \
+                curl -s -H "Authorization: token $$GH_TOKEN" -X POST -d @/workspace/api_payload.txt "https://api.github.com/repos/GoogleCloudPlatform/gke-poc-toolkit/issues/$_PR_NUMBER/comments"
+                exit 1
+              }
+          fi
+
           cd ../../
         done
       fi 
