Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -62,6 +62,7 @@ steps:
           echo "*************** TERRAFORM INIT ******************"
           echo "******* At environment: ${env} ********"
           echo "*************************************************"
+
           terraform init || exit 1
           cd ../../
         done
@@ -99,7 +100,10 @@ steps:
             rm provider.tf
           fi
 
-          terraform plan || exit 1
+          terraform plan || { 
+            echo 'my_command failed' 
+            exit 1 
+          }
           cd ../../
         done
       fi 
@@ -118,7 +122,6 @@ steps:
       apk add curl
       echo "{\"body\": \"Linting Complete - Ready for review\"}" > /workspace/api_payload.txt && \
       curl -s -H "Authorization: token $$GH_TOKEN" -X POST -d @/workspace/api_payload.txt "https://api.github.com/repos/albertwo1978/gke-poc-toolkit-1/issues/$_PR_NUMBER/comments"
-      exit 1
 
   secretEnv: ['GH_TOKEN']
 # [END completion-comment]
