test

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -63,10 +63,16 @@ steps:
           echo "******* At environment: ${env} ********"
           echo "*************************************************"
 
-          terraform init || exit 1
+          terraform plan || { 
+            apk add curl
+            echo "{\"body\": \"An error was detected executing \`terraform init\` against the **/terraform/${env}** directory. Please run \`terraform init\` locally against that directory to resolve any errors and then resubmit the Pull Request.\"}" > /workspace/api_payload.txt && \
+            curl -s -H "Authorization: token $$GH_TOKEN" -X POST -d @/workspace/api_payload.txt "https://api.github.com/repos/albertwo1978/gke-poc-toolkit-1/issues/$_PR_NUMBER/comments"
+            exit 1
+          }
           cd ../../
         done
       fi 
+  secretEnv: ['GH_TOKEN']
 # [END tf-init]
 
 # [START tf-plan]
